#pragma once

#include "utils.h"

#define MAX_NUM_PTS 300

#define MIN_CTRL_PTS_SIZE 1.0f
#define MAX_CTRL_PTS_SIZE 20.0f

#define DELAY 10.0f

#define CURSOR_NORMAL GLUT_CURSOR_RIGHT_ARROW
#define CURSOR_HOVER GLUT_CURSOR_DESTROY
#define CURSOR_DRAG GLUT_CURSOR_CYCLE