#pragma once

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define DELAY 0

#define PI 3.141592653589793

// Spaceship
#define SPACESHIP_SCALE 20.0f

#define SPACESHIP_MAX_FORWARD_SPEED 300.0f
#define SPACESHIP_MAX_ANGULAR_SPEED (PI * 2)
#define SPACESHIP_MIN_ANGULAR_SPEED (PI / 2)

#define SPACESHIP_FORWARD_DECELERATION 0.95f
#define SPACESHIP_ANGULAR_DECELERATION 0.8f
